[package]

name = "conduit-utils"
version = "0.5.0"
authors = ["wycats@gmail.com"]

[[lib]]

name = "conduit-utils"

[dependencies.conduit]

git = "https://github.com/conduit-rust/conduit.git"

[dependencies.conduit-test]

git = "https://github.com/conduit-rust/conduit-test.git"
